name: Upload Katalon Report

on:
  repository_dispatch:
    inputs:
      upload_count:
        description: 'Number of times to upload the report'
        required: true
        type: number
        default: 1
  workflow_dispatch:
    inputs:
      upload_count:
        description: 'Number of times to upload the report'
        required: true
        type: number
        default: 1

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate upload matrix
        id: set-matrix
        run: |
          count=${{ github.event.inputs.upload_count }}
          matrix=$(seq -s, 1 $count | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  upload-report:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        upload_number: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
      
    - name: Katalon Report Uploader (Upload #${{ matrix.upload_number }})
      run: |
        java -jar ${{ github.workspace }}/katalon-report-uploader-0.0.11.jar \
          --projectId=${{ secrets.PROJECT_ID }} \
          --path="${{ github.workspace }}/report" \
          --password=${{ secrets.KATALON_API_KEY }} \
          --type=katalon \
          --push-to-xray=false \
          --server=${{ secrets.KATALON_SERVER_URL }}
