name: Upload Katalon Report

on:
  workflow_dispatch:
    inputs:
      upload_count:
        description: 'Number of times to upload the report'
        required: true
        default: 1
        type: number

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate upload matrix
        id: set-matrix
        run: |
          count=${{ github.event.inputs.upload_count }}
          matrix=$(seq -s, 1 $count | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  upload-report:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        upload_number: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Katalon Report Uploader (Upload #${{ matrix.upload_number }})
      uses: katalon-studio/report-uploader@v0.0.11
      env:
        PASSWORD: ${{ secrets.KATALON_API_KEY }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        TYPE: katalon
        REPORT_PATH: ${{ github.workspace }}/report
        SEVER: ${{ secrets.KATALON_SERVER_URL }}
